// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfihtihpxhznkzxneupd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1maWh0aWhweGh6bmt6eG5ldXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTc1MzIsImV4cCI6MjA2MDAzMzUzMn0.Wu2Ee26M_rnFP94pzgik_YBs4rFAKIzsuHw6fY73FQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);